/**
 * Typed Tauri API wrapper for models commands.
 *
 * Auto-generated by scripts/gen-api-wrappers.mjs — do not edit manually.
 * Phase 15F.
 */

import { invoke } from "@tauri-apps/api/core";

export const Models = {
  /** @command: fetch_models */
  fetchModels: (forceRefresh: boolean) =>
    invoke<void>("fetch_models", {
        forceRefresh,
      }),

  /** @command: get_cached_models */
  getCachedModels: () =>
    invoke<void>("get_cached_models", {
      }),

} as const;
