/**
 * Typed Tauri API wrapper for unknown commands.
 *
 * Auto-generated by scripts/gen-api-wrappers.mjs — do not edit manually.
 * Phase 15F.
 */

import { invoke } from "@tauri-apps/api/core";

export const Unknown = {
  /** @command: synapse_call */
  synapseCall: (tool: string, args: any /* TODO: type for serde_json::Value */) =>
    invoke<void>("synapse_call", {
        tool,
        args,
      }),

  /** @command: check_synapse_available */
  checkSynapseAvailable: () =>
    invoke<boolean>("check_synapse_available", {
      }),

  /** @command: fetch_models */
  fetchModels: (forceRefresh: boolean) =>
    invoke<void>("fetch_models", {
        forceRefresh,
      }),

  /** @command: get_cached_models */
  getCachedModels: () =>
    invoke<void>("get_cached_models", {
      }),

} as const;
