// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppConfig = { latex: LaTeXConfig, synapse: SynapseConfig, chat: ChatConfig | null, ui: UIConfig | null, };

export type AppConfigModels = { providers: Array<ProviderConfig>, };

export type ChatConfig = { system_prompt: string | null, max_tokens: number | null, temperature: number | null, safety_mode: string | null, safety_min_trust: number | null, safety_max_total_bytes: number | null, };

export type LaTeXConfig = { engine: string, };

export type ProviderConfig = { name: string, enabled: boolean, env_key: string | null, stored_api_key: string | null, base_url: string, models: Array<string>, default_model: string, fetch_models: boolean, };

export type SynapseConfig = { vaults: Array<VaultConfig> | null, study_log_path: string | null, };

export type UIConfig = { font_size: number | null, };

export type VaultConfig = { name: string, path: string, };
