// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A memory item in the learner profile.
 */
export type MemoryItem = { id: string, session_id: string | null, source_type: string, unit_type: string, content: string, score: number, created_at: string, tags: Array<string>, provenance: string | null, 
/**
 * Scan status persisted at write time ("accepted", "accepted_with_redaction",
 * "rejected"). Written by `store_memory_with_safety`; absent for legacy items.
 */
scan_status: string | null, scan_reason: string | null, };

/**
 * Safety mode for memory scanning.
 */
export type SafetyMode = "strict" | "balanced" | "off";

export type ScanResult = { kind: ScanResultKind, reason: string | null, redacted: string | null, };

/**
 * Result of scanning memory content for injection patterns.
 */
export type ScanResultKind = "accepted" | "accepted_with_redaction" | "rejected";
