// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * A content part within a message (text or image).
 */
export type ContentPart = { "type": "text", text: string, } | { "type": "image", 
/**
 * Optional disk-reference filename (from save_image). May be absent
 * when image data is sent inline via the `data` field.
 */
url: string | null, mime: string | null, data: string | null, };

/**
 * A single message in the conversation.
 */
export type Message = { id: string, role: string, segments: Array<MessageSegment>, content: Array<ContentPart>, created_at: string | null, flags: { [key in string]?: boolean } | null, 
/**
 * Legacy thinking field — preserved for backward compat reads.
 * New messages should use `segments` with type "thinking" instead.
 */
thinking: string | null, 
/**
 * For role="tool" messages: the ID of the tool call this result satisfies.
 */
tool_call_id: string | null, };

/**
 * An ordered segment within an assistant message's timeline.
 */
export type MessageSegment = { id: string, ts: string, } & ({ "type": "thinking", content: string, } | { "type": "tool_call", tool_name: string, arguments: JsonValue, call_id: string, status: ToolCallStatus, } | { "type": "tool_result", call_id: string, result: JsonValue, is_error: boolean, } | { "type": "content", text: string, });

/**
 * The kind/type of a message segment.
 */
export type SegmentKind = { "type": "thinking", content: string, } | { "type": "tool_call", tool_name: string, arguments: JsonValue, call_id: string, status: ToolCallStatus, } | { "type": "tool_result", call_id: string, result: JsonValue, is_error: boolean, } | { "type": "content", text: string, };

/**
 * Full session — header + messages.
 */
export type Session = { header: SessionHeader, messages: Array<Message>, };

/**
 * Mirrors the Swift `SessionHeader` model for backward compat.
 */
export type SessionHeader = { id: string, title: string, model: string, provider: string, created_at: string, updated_at: string, project_id: string | null, tutor_style: string | null, flags: { [key in string]?: boolean } | null, };

/**
 * Status of a tool call in the timeline.
 */
export type ToolCallStatus = "pending" | "running" | "completed" | "error";
