/**
 * HTML sanitization wrapper around DOMPurify.
 *
 * KaTeX generates safe inline styles and elements, but we configure
 * DOMPurify to be permissive enough to allow:
 *   - MathML elements (<math>, <mi>, <mo>, <mn>, etc.)
 *   - SVG elements/attributes (used by some KaTeX renderings)
 *   - Inline styles generated by KaTeX (color, background, etc.)
 *
 * The goal is to prevent XSS from model-injected HTML without breaking
 * markdown/LaTeX rendering.
 */

import DOMPurify from "dompurify";

// ─── URL Scheme Allowlist ────────────────────────────────────────────
//
// These schemes are permitted in href/src attributes. Everything else
// (javascript:, vbscript:, data: on anchors, file:, blob:) is stripped.

const ALLOWED_HREF_SCHEMES = ["http:", "https:", "mailto:"];
const ALLOWED_SRC_SCHEMES = ["data:", "asset:"];
const DATA_IMAGE_MIME = /^data:image\/(png|jpe?g|gif|webp|svg\+xml);/i;

/**
 * Validate a URL against the scheme allowlist for the given attribute kind.
 * Returns the original URL if allowed, null if it should be stripped.
 */
export function safeUrl(raw: string, kind: "href" | "src"): string | null {
  if (!raw) return null;
  const trimmed = raw.trim();
  // Allow relative URLs, fragment-only, and scheme-relative
  if (
    trimmed.startsWith("#") ||
    trimmed.startsWith("/") ||
    !trimmed.includes(":")
  )
    return raw;

  let url: URL;
  try {
    url = new URL(trimmed);
  } catch {
    return null;
  } // not parseable → drop

  const proto = url.protocol.toLowerCase();

  if (kind === "href") {
    if (ALLOWED_HREF_SCHEMES.includes(proto)) return raw;
    // data: on anchors is never allowed
    return null;
  }

  // kind === "src"
  if (ALLOWED_SRC_SCHEMES.includes(proto)) {
    if (proto === "data:" && !DATA_IMAGE_MIME.test(raw)) return null;
    return raw;
  }
  return null;
}

// ─── DOMPurify Hook: URL validation + anchor rel injection ─────────
//
// This hook runs AFTER DOMPurify has already filtered tags/attrs.
// We validate URL-shaped attributes against the scheme allowlist.

DOMPurify.addHook("afterSanitizeAttributes", (node) => {
  // 1. Validate / rewrite URL attributes
  for (const attr of ["href", "src"] as const) {
    if (!node.hasAttribute(attr)) continue;
    const kind = attr === "href" ? "href" : ("src" as const);
    const safe = safeUrl(node.getAttribute(attr)!, kind);
    if (safe === null) {
      node.removeAttribute(attr);
    } else {
      node.setAttribute(attr, safe);
    }
  }

  // Special handling for SVG xlink:href (deprecated but still used by some SVGs)
  if (node.hasAttributeNS && node.hasAttributeNS("http://www.w3.org/1999/xlink", "href")) {
    const val = node.getAttributeNS("http://www.w3.org/1999/xlink", "href");
    if (val && safeUrl(val, "src") === null) {
      node.removeAttributeNS("http://www.w3.org/1999/xlink", "href");
    }
  }

  // 2. Auto-inject rel="noopener noreferrer" on anchors with target
  if (node.tagName === "A" && node.hasAttribute("target")) {
    const existing = (node.getAttribute("rel") || "")
      .toLowerCase()
      .split(/\s+/)
      .filter(Boolean);
    const need = ["noopener", "noreferrer"].filter(
      (t) => !existing.includes(t)
    );
    if (need.length > 0) {
      const merged = [...existing, ...need].join(" ");
      node.setAttribute("rel", merged);
    }
  }
});

// ─── KaTeX-Safe configuration ────────────────────────────────────────────────
//
// KaTeX generates elements such as:
//   <span class="katex"> ... <span class="katex-mathml">...</span> ...
//   <annotation encoding="application/x-tex">...</annotation>
//   SVG for fractions, accents, etc.
//   Inline style attributes (e.g. style="color:...")
//
// The config below allows these through while stripping dangerous HTML.

const ALLOWED_TAGS = [
  // KaTeX structural
  "span",
  "div",
  "semantics",
  "annotation",
  "math",
  "menclose",
  "merror",
  "mfenced",
  "mfrac",
  "mi",
  "mmultiscripts",
  "mn",
  "mo",
  "mover",
  "mpadded",
  "mphantom",
  "mroot",
  "mrow",
  "ms",
  "mspace",
  "msqrt",
  "mstyle",
  "msub",
  "msubsup",
  "msup",
  "mtable",
  "mtd",
  "mtext",
  "mtr",
  "munder",
  "munderover",
  "none",
  "prescripts",

  // SVG (used by some KaTeX paths)
  "svg",
  "g",
  "path",
  "line",
  "circle",
  "rect",
  "polygon",
  "polyline",
  "text",
  "tspan",
  "defs",
  "use",
  "clipPath",
  "mask",
  "linearGradient",
  "radialGradient",
  "stop",
  "marker",
  "filter",
  "feGaussianBlur",
  "feOffset",
  "feMerge",
  "feMergeNode",
  "feFlood",
  "feComposite",
  "feBlend",

  // Markdown-rendered HTML
  "p",
  "br",
  "hr",
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "ul",
  "ol",
  "li",
  "dl",
  "dt",
  "dd",
  "blockquote",
  "pre",
  "code",
  "tt",
  "kbd",
  "samp",
  "var",
  "table",
  "thead",
  "tbody",
  "tfoot",
  "tr",
  "th",
  "td",
  "caption",
  "colgroup",
  "col",
  "a",
  "abbr",
  "address",
  "b",
  "bdi",
  "bdo",
  "big",
  "cite",
  "data",
  "del",
  "dfn",
  "em",
  "i",
  "img",
  "ins",
  "mark",
  "q",
  "rp",
  "rt",
  "ruby",
  "s",
  "samp",
  "small",
  "source",
  "strong",
  "sub",
  "summary",
  "sup",
  "time",
  "u",
  "wbr",
  "details",
];

const ALLOWED_ATTR = [
  // KaTeX span attributes
  "class",
  "style",
  "aria-hidden",
  "aria-label",
  "role",
  "dir",

  // MathML
  "xmlns",
  "encoding",
  "displaystyle",
  "scriptlevel",
  "mathvariant",
  "lspace",
  "rspace",
  "stretchy",
  "symmetric",
  "maxsize",
  "minsize",
  "largeop",
  "movablelimits",
  "separator",
  "accent",
  "accentunder",
  "fence",
  "texclass",
  "linethickness",
  "numalign",
  "denomalign",
  "bevelled",
  "rowalign",
  "columnalign",
  "groupalign",
  "align",
  "columnwidth",
  "width",
  "height",
  "depth",
  "rowspan",
  "columnspan",
  "frame",
  "frame spacing",
  "cellspacing",
  "columnlines",
  "rowlines",
  "frame line",

  // SVG
  "d",
  "fill",
  "stroke",
  "preserveAspectRatio",
  "stroke-width",
  "stroke-linecap",
  "stroke-linejoin",
  "transform",
  "viewBox",
  "cx",
  "cy",
  "r",
  "rx",
  "ry",
  "x",
  "y",
  "dx",
  "dy",
  "x1",
  "y1",
  "x2",
  "y2",
  "points",
  "opacity",
  "clip-path",
  "mask",
  "fill-opacity",
  "stroke-opacity",
  "stroke-dasharray",
  "stroke-dashoffset",
  "text-anchor",
  "dominant-baseline",
  "font-family",
  "font-size",
  "font-weight",
  "font-style",
  "href",
  "target",

  // Markdown links / images
  "href",
  "src",
  "alt",
  "title",
  "rel",

  // Tables
  "colspan",
  "rowspan",
  "headers",
  "scope",
  "abbr",
  "summary",

  // Inputs
  "type",
  "name",
  "value",
  "disabled",
  "readonly",
  "checked",
  "placeholder",
  "required",
  "max",
  "min",
  "maxlength",
  "size",
  "step",
  "autocomplete",
  "autofocus",

  // Details / summary
  "open",

  // General
  "lang",
  "xml:lang",
  "data-*", // Allow all data-* attributes
];

/**
 * Sanitize HTML string with KaTeX-safe DOMPurify configuration.
 * Returns clean HTML safe for `dangerouslySetInnerHTML`.
 */
export function sanitize(html: string): string {
  return DOMPurify.sanitize(html, {
    ALLOWED_TAGS,
    ALLOWED_ATTR,
    ALLOW_DATA_ATTR: true,
    // Allow style attributes (KaTeX uses inline styles extensively)
    ALLOW_UNKNOWN_PROTOCOLS: false,
    ADD_ATTR: ["target"],
    // Strip <style> tags but keep inline styles on elements
    FORBID_TAGS: ["style", "script", "iframe", "object", "embed", "form"],
    FORBID_ATTR: [
      "onerror",
      "onload",
      "onclick",
      "onmouseover",
      "onmouseout",
      "onfocus",
      "onblur",
      "onsubmit",
      "onchange",
      "oninput",
      "formaction",
      "ping",
      "autofocus",
      "formmethod",
      "formenctype",
      "formtarget",
      "formnovalidate",
    ],
    // Prevent prototype/constructor access via data URIs
    SANITIZE_DOM: true,
    // NOTE: Do NOT set USE_PROFILES here. DOMPurify's USE_PROFILES resets
    // ALLOWED_TAGS entirely before adding the profile's tags, discarding all
    // our custom SVG/MathML entries. KaTeX renders \sqrt as an <svg><path>,
    // which USE_PROFILES: { html: true } silently strips. Our explicit
    // ALLOWED_TAGS + ALLOWED_ATTR lists above are sufficient and correct.
  });
}

export default sanitize;
