// ─── Problem Bank Service (Phase 16B) ────────────────────────────────
//
// Loads the bundled problem bank JSON, provides filtering/querying, and
// persists attempt records to disk.
//
// Problem bank is embedded at compile time via `include_str!` so it works
// fully offline with no runtime dependencies.

use std::path::PathBuf;

use chrono::Utc;
use rand::seq::SliceRandom;

use crate::pathscope;

use crate::error::AppError;
use serde::{Deserialize, Serialize};
#[cfg(feature = "export-types")]
use ts_rs::TS;

// ─── Problem record ───────────────────────────────────────────────────

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[cfg_attr(feature = "export-types", derive(TS))]
#[cfg_attr(feature = "export-types", ts(export, export_to = "problem_bank.ts"))]
pub enum ProblemSource {
    Imo,
    Usamo,
    Aime,
    Amc,
    Putnam,
    Custom,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[cfg_attr(feature = "export-types", derive(TS))]
#[cfg_attr(feature = "export-types", ts(export, export_to = "problem_bank.ts"))]
pub enum DifficultyTier {
    Amc,
    Aime,
    UsamoEasy,
    UsamoHard,
    ImoEasy,
    ImoHard,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[cfg_attr(feature = "export-types", derive(TS))]
#[cfg_attr(feature = "export-types", ts(export, export_to = "problem_bank.ts"))]
pub enum ProblemTopic {
    Combinatorics,
    NumberTheory,
    Algebra,
    Geometry,
    Inequalities,
    FunctionalEquations,
    Probability,
    Other,
}

/// A single curated competition problem.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "export-types", derive(TS))]
#[cfg_attr(feature = "export-types", ts(export, export_to = "problem_bank.ts"))]
pub struct CompProblem {
    pub id: String,
    pub source: ProblemSource,
    pub year: u32,
    pub number: u8,
    pub difficulty: DifficultyTier,
    pub topics: Vec<ProblemTopic>,
    pub statement: String,
    pub answer: Option<String>,
    pub solution_sketch: Option<String>,
}

/// Filter passed from the frontend for querying problems.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "export-types", derive(TS))]
#[cfg_attr(feature = "export-types", ts(export, export_to = "problem_bank.ts"))]
pub struct ProblemFilter {
    pub topics: Option<Vec<ProblemTopic>>,
    pub difficulties: Option<Vec<DifficultyTier>>,
    pub sources: Option<Vec<ProblemSource>>,
    pub exclude_ids: Option<Vec<String>>,
    pub limit: Option<usize>,
}

// ─── Attempt record ───────────────────────────────────────────────────

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[cfg_attr(feature = "export-types", derive(TS))]
#[cfg_attr(feature = "export-types", ts(export, export_to = "problem_bank.ts"))]
pub enum AttemptOutcome {
    Solved,
    PartialProgress,
    Stuck,
    GaveUp,
}

/// A single problem attempt by the student.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "export-types", derive(TS))]
#[cfg_attr(feature = "export-types", ts(export, export_to = "problem_bank.ts"))]
pub struct ProblemAttempt {
    pub problem_id: String,
    pub session_id: String,
    pub timestamp: String,
    pub elapsed_seconds: u32,
    pub outcome: AttemptOutcome,
    pub hints_used: u8,
    pub notes: String,
}

/// Aggregate stats for the Overview page.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "export-types", derive(TS))]
#[cfg_attr(feature = "export-types", ts(export, export_to = "problem_bank.ts"))]
pub struct AttemptStats {
    pub total_attempted: u32,
    pub solved: u32,
    pub partial: u32,
    pub stuck: u32,
    pub gave_up: u32,
    pub by_topic: Vec<TopicStat>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "export-types", derive(TS))]
#[cfg_attr(feature = "export-types", ts(export, export_to = "problem_bank.ts"))]
pub struct TopicStat {
    pub topic: String,
    pub attempted: u32,
    pub solved: u32,
}

// ─── Static problem bank (embedded) ───────────────────────────────────

/// The bundled problem bank JSON. Embedded at compile time.
/// Generated by a build script or curated as a checked-in file.
const BUNDLED_PROBLEM_BANK: &str = include_str!("../../resources/problem-bank.json");

// ─── ProblemBankService ───────────────────────────────────────────────

pub struct ProblemBankService {
    base_dir: PathBuf,
    problems: Vec<CompProblem>,
}

impl ProblemBankService {
    pub fn new(base_dir: PathBuf) -> Self {
        let problems: Vec<CompProblem> = serde_json::from_str(BUNDLED_PROBLEM_BANK)
            .unwrap_or_else(|e| {
                eprintln!("[problem_bank] Failed to parse bundled problem bank: {}", e);
                vec![]
            });

        Self { base_dir, problems }
    }

    // ── Query methods ─────────────────────────────────────────────────

    /// List problems matching the given filter.
    pub fn list_problems(&self, filter: ProblemFilter) -> Result<Vec<CompProblem>, AppError> {
        let mut results: Vec<CompProblem> = self
            .problems
            .iter()
            .filter(|p| {
                if let Some(ref topics) = filter.topics {
                    if !p.topics.iter().any(|t| topics.contains(t)) {
                        return false;
                    }
                }
                if let Some(ref diffs) = filter.difficulties {
                    if !diffs.contains(&p.difficulty) {
                        return false;
                    }
                }
                if let Some(ref sources) = filter.sources {
                    if !sources.contains(&p.source) {
                        return false;
                    }
                }
                if let Some(ref exclude) = filter.exclude_ids {
                    if exclude.contains(&p.id) {
                        return false;
                    }
                }
                true
            })
            .cloned()
            .collect();

        // Apply limit
        if let Some(limit) = filter.limit {
            results.truncate(limit);
        }

        Ok(results)
    }

    /// Get a single problem by ID.
    pub fn get_problem(&self, id: &str) -> Result<CompProblem, AppError> {
        self.problems
            .iter()
            .find(|p| p.id == id)
            .cloned()
            .ok_or_else(|| AppError::not_found(format!("Problem '{}' not found in bank", id)))
    }

    /// Pick a random problem matching the filter.
    pub fn random_problem(&self, filter: ProblemFilter) -> Result<CompProblem, AppError> {
        let matching = self.list_problems(filter)?;
        let mut rng = rand::thread_rng();
        matching
            .choose(&mut rng)
            .cloned()
            .ok_or_else(|| AppError::not_found("No problems match the given filter".to_string()))
    }

    // ── Attempt persistence ────────────────────────────────────────────

    fn attempts_dir(&self) -> PathBuf {
        let mut p = self.base_dir.clone();
        p.push("attempts");
        let _ = std::fs::create_dir_all(&p);
        p
    }

    fn attempt_path(&self, problem_id: &str, session_id: &str) -> PathBuf {
        self.attempts_dir()
            .join(format!("{}_{}.json", problem_id, session_id))
    }

    /// Save a problem attempt to disk.
    pub fn save_attempt(&self, attempt: ProblemAttempt) -> Result<(), AppError> {
        let path = self.attempt_path(&attempt.problem_id, &attempt.session_id);
        let data = serde_json::to_string_pretty(&attempt)
            .map_err(|e| AppError::internal(format!("Failed to serialize attempt: {}", e)))?;
        std::fs::write(&path, data)
            .map_err(|e| AppError::internal(format!("Failed to save attempt: {}", e)))?;
        Ok(())
    }

    /// List all problem attempts, optionally filtered by problem ID.
    pub fn list_attempts(&self, problem_id: Option<&str>) -> Result<Vec<ProblemAttempt>, AppError> {
        let dir = self.attempts_dir();
        let entries = std::fs::read_dir(&dir)
            .map_err(|e| AppError::internal(format!("Failed to read attempts dir: {}", e)))?;

        let mut attempts: Vec<ProblemAttempt> = Vec::new();
        for entry in entries.flatten() {
            let path = entry.path();
            if path.extension().map_or(true, |e| e != "json") {
                continue;
            }
            if let Some(pid) = problem_id {
                if !path
                    .file_stem()
                    .map_or(true, |s| s.to_string_lossy().starts_with(pid))
                {
                    continue;
                }
            }
            if let Ok(data) = std::fs::read_to_string(&path) {
                if let Ok(attempt) = serde_json::from_str::<ProblemAttempt>(&data) {
                    attempts.push(attempt);
                }
            }
        }

        attempts.sort_by(|a, b| b.timestamp.cmp(&a.timestamp));
        Ok(attempts)
    }

    /// Compute aggregate attempt stats.
    pub fn get_attempt_stats(&self) -> Result<AttemptStats, AppError> {
        let all = self.list_attempts(None)?;
        let total = all.len() as u32;
        let solved = all.iter().filter(|a| a.outcome == AttemptOutcome::Solved).count() as u32;
        let partial = all.iter().filter(|a| a.outcome == AttemptOutcome::PartialProgress).count() as u32;
        let stuck = all.iter().filter(|a| a.outcome == AttemptOutcome::Stuck).count() as u32;
        let gave_up = all.iter().filter(|a| a.outcome == AttemptOutcome::GaveUp).count() as u32;

        // Compute topic stats
        let mut topic_map: std::collections::HashMap<String, (u32, u32)> = std::collections::HashMap::new();
        for attempt in &all {
            // Look up problem topics
            if let Ok(problem) = self.get_problem(&attempt.problem_id) {
                for topic in &problem.topics {
                    let key = format!("{:?}", topic);
                    let entry = topic_map.entry(key).or_insert((0, 0));
                    entry.0 += 1;
                    if attempt.outcome == AttemptOutcome::Solved {
                        entry.1 += 1;
                    }
                }
            }
        }

        let by_topic: Vec<TopicStat> = topic_map
            .into_iter()
            .map(|(topic, (attempted, solved))| TopicStat {
                topic,
                attempted,
                solved,
            })
            .collect();

        Ok(AttemptStats {
            total_attempted: total,
            solved,
            partial,
            stuck,
            gave_up,
            by_topic,
        })
    }

    // ── Vault note generation ────────────────────────────────────────

    /// Save a problem attempt as a vault note (markdown with YAML frontmatter).
    /// The note is written to `<vault>/MathMate/Competition/Attempts/<problem_id>.md`.
    pub fn save_attempt_note(
        &self,
        problem_id: &str,
        source: &str,
        year: u32,
        number: u8,
        difficulty: &str,
        topics: &[String],
        statement: &str,
        outcome: &str,
        hints_used: u8,
        elapsed_seconds: u32,
        notes: &str,
        vault_path: &str,
    ) -> Result<String, AppError> {
        let now = Utc::now();
        let date_str = now.format("%Y-%m-%d").to_string();
        let minutes = elapsed_seconds / 60;

        let topic_list = topics
            .iter()
            .map(|t| format!("  - {:?}", t))
            .collect::<Vec<_>>()
            .join("\n");

        let outcome_display = match outcome {
            "Solved" => "solved",
            "PartialProgress" => "partial",
            "Stuck" => "stuck",
            "GaveUp" => "gave-up",
            _ => outcome,
        };

        let note = format!(
            "---\ntype: problem-attempt\nproblem_id: {problem_id}\nsource: \"{source}\"\nyear: {year}\nnumber: {number}\ndifficulty: \"{difficulty}\"\ntopic:\n{topic_list}\noutcome: {outcome_display}\nhints_used: {hints_used}\ntime_minutes: {minutes}\ndate: {date_str}\n---\n\n## Problem\n\n{statement}\n\n## My Approach\n\n{notes}\n\n## What I Learned\n\n"
        );

        // Build target path inside vault
        let mut target = PathBuf::from(vault_path);
        target.push("MathMate");
        target.push("Competition");
        target.push("Attempts");
        let _ = std::fs::create_dir_all(&target);
        target.push(format!("{}.md", problem_id));

        // Security check: ensure target is inside vault
        let safe_target = pathscope::ensure_inside_vault(vault_path, &target)
            .map_err(|e| AppError::internal(format!("Path containment check failed: {}", e)))?;

        std::fs::write(&safe_target, note.as_bytes())
            .map_err(|e| AppError::internal(format!("Failed to write attempt note: {}", e)))?;

        Ok(safe_target.to_string_lossy().to_string())
    }
}

// ─── Helper ───────────────────────────────────────────────────────────

impl ProblemFilter {
    pub fn empty() -> Self {
        Self {
            topics: None,
            difficulties: None,
            sources: None,
            exclude_ids: None,
            limit: None,
        }
    }
}

impl Default for ProblemFilter {
    fn default() -> Self {
        Self::empty()
    }
}