// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type FunctionDef = { name: string, description: string, parameters: JsonValue, };

/**
 * A tool call emitted by the model during streaming.
 */
export type ToolCall = { call_id: string, tool_name: string, arguments: JsonValue, };

/**
 * OpenAI-compatible tool definition for function calling.
 */
export type ToolDefinition = { type: string, function: FunctionDef, };

/**
 * The result of executing a tool.
 */
export type ToolResult = { call_id: string, result: JsonValue, is_error: boolean, };
