use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::path::PathBuf;

use crate::{audit, pathscope, session};

/// Result of a wrap-up generation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WrapUpResult {
    pub session_id: String,
    pub title: String,
    pub study_log_path: Option<String>,
    pub content: String,
    pub created_at: String,
}

/// Banner prefix for all auto-generated study logs.
const AUTO_GENERATED_BANNER: &str =
    "<!-- AUTO-GENERATED by MathMate v2 — DO NOT EDIT — re-run /wrap-up to regenerate -->";

/// Build the study log file path from a vault path and timestamp.
fn build_target_path(vault_path: &str, now: &DateTime<Utc>) -> PathBuf {
    let date_str = now.format("%Y-%m-%d").to_string();
    let year = now.format("%Y").to_string();
    let month = now.format("%m-%B").to_string(); // e.g., "05-May"

    let mut dir = PathBuf::from(vault_path);
    dir.push("MathMate");
    dir.push("Study Logs");
    dir.push(&year);
    dir.push(&month);

    let filename = format!("Study Log - {}.md", date_str);
    dir.join(&filename)
}

/// Prepend the auto-generated banner + metadata comment block to the content.
fn prepend_banner(content: &str, session_id: &str, now: &DateTime<Utc>) -> String {
    let timestamp = now.to_rfc3339();
    let hash = sha256_hex(content.as_bytes());
    format!(
        "{}\n<!-- session_id: {} -->\n<!-- content_sha256: {} -->\n<!-- generated_at: {} -->\n\n{}",
        AUTO_GENERATED_BANNER, session_id, hash, timestamp, content,
    )
}

/// Compute SHA-256 hex digest of a byte slice.
fn sha256_hex(data: &[u8]) -> String {
    let mut hasher = Sha256::new();
    hasher.update(data);
    hex_encode(&hasher.finalize())
}

/// Minimal hex encoding for a byte slice (avoids pulling in the `hex` crate).
fn hex_encode(bytes: &[u8]) -> String {
    const HEX_CHARS: &[u8] = b"0123456789abcdef";
    let mut out = Vec::with_capacity(bytes.len() * 2);
    for &b in bytes {
        out.push(HEX_CHARS[(b >> 4) as usize]);
        out.push(HEX_CHARS[(b & 0x0f) as usize]);
    }
    // SAFETY: the hex chars are all valid ASCII
    unsafe { String::from_utf8_unchecked(out) }
}

/// Generate a study log markdown from a session.
/// Uses a template-based approach (no model call) for Phase 2.
/// Phase 5 enhancement: use model for intelligent summarization.
pub fn generate_wrap_up(session_id: &str) -> Result<WrapUpResult, String> {
    let session_data = session::load_session(session_id)?;
    let now = Utc::now().to_rfc3339();

    // Extract user messages
    let user_messages: Vec<String> = session_data
        .messages
        .iter()
        .filter(|m| m.role == "user")
        .map(|m| {
            m.content
                .iter()
                .filter_map(|part| match part {
                    session::ContentPart::Text { text } => Some(text.as_str()),
                    _ => None,
                })
                .collect::<Vec<_>>()
                .join("\n")
        })
        .collect::<Vec<_>>();

    // Extract key topics from user messages (simple: first few words of each message)
    let topics: Vec<&str> = user_messages
        .iter()
        .filter_map(|msg| msg.split_whitespace().next())
        .take(5)
        .collect();

    let message_count = session_data.messages.len();
    let question_count = user_messages.len();

    let content = format!(
        "## Study Log

**Session**: {}  
**Date**: {}  
**Model**: {} / {}  
**Messages**: {} ({} questions)  

### Topics Covered

{}

### Summary

This session covered {} questions with {} total messages. Key topics included: {}.

### Key Concepts

- Review the questions and answers in the session log
- Practice similar problems to reinforce understanding
- Use flashcards for any formulas or theorems encountered

---

*Auto-generated study log from MathMate v2*
",
        session_data.header.title,
        session_data.header.created_at,
        session_data.header.provider,
        session_data.header.model,
        message_count,
        question_count,
        if topics.is_empty() {
            "No specific topics identified.".to_string()
        } else {
            topics
                .iter()
                .map(|t| format!("- {}", t.trim_matches(|c: char| c.is_ascii_punctuation())))
                .collect::<Vec<_>>()
                .join("\n")
        },
        question_count,
        message_count,
        if topics.is_empty() {
            "general mathematics".to_string()
        } else {
            topics.join(", ")
        },
    );

    Ok(WrapUpResult {
        session_id: session_id.to_string(),
        title: session_data.header.title,
        study_log_path: None,
        content,
        created_at: now,
    })
}

/// Save a wrap-up study log with path containment checks, banner, and audit log.
///
/// Uses the vault path from the caller (currently request-driven from the frontend).
/// A future enhancement should resolve the vault path from backend project/session state.
pub fn save_wrap_up(
    _project_name: &str,
    vault_path: &str,
    content: &str,
) -> Result<String, String> {
    let now = Utc::now();

    // Build the target path from vault + date
    let target = build_target_path(vault_path, &now);

    // Containment check: ensure target is inside vault
    let safe_target = pathscope::ensure_inside_vault(vault_path, &target)?;

    // Prepend banner with session id and content hash
    let session_id = "unknown"; // TODO: plumb session_id through from caller
    let annotated = prepend_banner(content, session_id, &now);

    // Write the file
    std::fs::write(&safe_target, annotated.as_bytes())
        .map_err(|e| format!("Failed to write study log: {}", e))?;

    // Audit log
    let hash = sha256_hex(content.as_bytes());
    let _ = audit::log_wrapup(
        &now.to_rfc3339(),
        session_id,
        vault_path,
        &safe_target.to_string_lossy(),
        annotated.len(),
        &hash,
    );

    Ok(safe_target.to_string_lossy().to_string())
}

// ─── Tests ───────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_prepend_banner_includes_banner() {
        let result = prepend_banner("Hello world", "sess-1", &Utc::now());
        assert!(result.contains(AUTO_GENERATED_BANNER));
        assert!(result.contains("Hello world"));
        assert!(result.contains("sess-1"));
        assert!(result.contains("content_sha256"));
    }

    #[test]
    fn test_build_target_path_format() {
        let now = Utc::now();
        let path = build_target_path("/tmp/vault", &now);
        let path_str = path.to_string_lossy();
        assert!(path_str.starts_with("/tmp/vault/MathMate/Study Logs/"));
        assert!(path_str.ends_with(".md"));
        assert!(path_str.contains(&now.format("%Y-%m-%d").to_string()));
    }

    #[test]
    fn test_sha256_hex_length() {
        let hash = sha256_hex(b"test data");
        assert_eq!(hash.len(), 64); // SHA-256 hex is 64 chars
    }

    #[test]
    fn test_sha256_hex_deterministic() {
        let a = sha256_hex(b"hello");
        let b = sha256_hex(b"hello");
        assert_eq!(a, b);
    }

    #[test]
    fn test_hex_encode() {
        assert_eq!(hex_encode(&[0xFF, 0x00, 0xAB]), "ff00ab");
        assert_eq!(hex_encode(b"ABC"), "414243");
    }
}
